title: Kate Thornhill, MLS
description: Public Scholarship Librarian · Geospatial Scientist ·Digital Humanities · Eugene, Oregon
email: thornhik@oregonstate.edu
show_downloads: false
theme: jekyll-theme-minimal

# Profile photo
photo: /assets/img/profile.png
