title: Kate Thornhill, MLS
description: Geography & Geospatial Science Graduate Student · Digital Humanities · Academic Librarian · Eugene, Oregon
email: thornhik@oregonstate.edu
show_downloads: false
theme: jekyll-theme-minimal

# Profile photo
photo: /assets/img/profile.png
